# Generated by Django 2.0.4 on 2018-05-14 17:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('Week', 'Weekly target'), ('Day', 'Daily target'), ('Verify', 'Verify'), ('Done', 'Done')], default='Week', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScrummyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('target_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.GoalStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ScrummyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='scrummygoals',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ScrummyUser'),
        ),
    ]
