# Generated by Django 2.1.5 on 2019-06-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrummyuser',
            name='org',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='myapp.Admin'),
        ),
    ]
