# Generated by Django 2.0.4 on 2018-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='target',
            field=models.CharField(choices=[('Week', 'Weekly target'), ('Day', 'Daily target'), ('Verify', 'Verify'), ('Done', 'Done')], max_length=100),
        ),
    ]
